# Generated by Django 4.1.1 on 2022-10-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=10)),
                ("month", models.CharField(max_length=10)),
                ("motouke", models.CharField(max_length=20)),
                ("place", models.CharField(max_length=20)),
                ("color_number", models.CharField(max_length=30)),
                ("other", models.CharField(max_length=70)),
            ],
        ),
    ]
