# Generated by Django 4.1.1 on 2022-12-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="information",
            name="month",
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name="information",
            name="year",
            field=models.IntegerField(max_length=10),
        ),
    ]
