# Generated by Django 4.1.1 on 2022-10-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="information",
            name="month",
            field=models.CharField(
                choices=[
                    ("1月", "1月"),
                    ("2月", "2月"),
                    ("3月", "3月"),
                    ("4月", "4月"),
                    ("5月", "5月"),
                    ("6月", "6月"),
                    ("7月", "7月"),
                    ("8月", "8月"),
                    ("9月", "9月"),
                    ("10月", "10月"),
                    ("11月", "11月"),
                    ("12月", "12月"),
                ],
                max_length=10,
            ),
        ),
    ]
