# Generated by Django 4.1.1 on 2022-10-22 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("informations", "0002_alter_information_month"),
    ]

    operations = [
        migrations.DeleteModel(name="Information",),
    ]
