# Generated by Django 4.1.1 on 2022-10-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informations", "0004_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="information",
            name="kouzi",
            field=models.CharField(default="", max_length=20),
        ),
    ]
