# Generated by Django 4.1.1 on 2022-12-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "alcohol",
                    models.CharField(
                        choices=[
                            ("アルコール検知: 0.00mg", "0.00mg"),
                            ("アルコール検知: 0.15mg未満", "0.15mg未満"),
                            ("アルコール検知: 0.15mg以上", "0.15mg以上"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "carnumber",
                    models.CharField(
                        choices=[
                            ("6882", "6882"),
                            ("2151", "2151"),
                            ("2532", "2532"),
                            ("5173", "5173"),
                            ("5999", "5999"),
                            ("386", "386"),
                            ("783", "783"),
                            ("2569", "2569"),
                            ("777", "777"),
                            ("3080", "3080"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
