# Generated by Django 4.1.1 on 2024-05-24 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "alcohol",
                    models.CharField(
                        choices=[
                            ("アルコール検知: 0.00mg", "0.00mg"),
                            ("アルコール検知: 0.15mg未満", "0.15mg未満"),
                            ("アルコール検知: 0.15mg以上", "0.15mg以上"),
                        ],
                        max_length=20,
                    ),
                ),
                ("carnumber", models.IntegerField(choices=[(3080, 3080)])),
                (
                    "varified_by",
                    models.CharField(
                        choices=[("武村 義治", "武村 義治"), ("武村 俊二", "武村 俊二")], max_length=10
                    ),
                ),
                (
                    "how_to",
                    models.CharField(
                        choices=[("対面", "対面"), ("ビデオ通話", "ビデオ通話")], max_length=20
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
