# Generated by Django 4.1.1 on 2024-05-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alcoholchecks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="info",
            name="a",
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
