# Generated by Django 4.1.1 on 2022-09-15 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("alcoholchecks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="info",
            name="month",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="alcoholchecks.month",
            ),
        ),
    ]
