# Generated by Django 4.1.1 on 2022-12-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alcoholchecks", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="carnumber",
            field=models.IntegerField(choices=[(1, 1)]),
        ),
    ]
