# Generated by Django 4.1.1 on 2024-05-24 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alcoholchecks", "0002_info_a"),
    ]

    operations = [
        migrations.RemoveField(model_name="info", name="a",),
    ]
