# Generated by Django 4.1.1 on 2022-09-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alcoholchecks", "0002_info_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="alcohol",
            field=models.CharField(
                choices=[("1", "yes"), ("2", "no")], max_length=20, null=True
            ),
        ),
    ]
