# Generated by Django 4.1.1 on 2022-09-17 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("alcoholchecks", "0003_alter_info_alcohol"),
    ]

    operations = [
        migrations.AddField(
            model_name="month",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="info",
            name="alcohol",
            field=models.CharField(
                choices=[("アルコール検知なし", "あり"), ("アルコール検知なし", "なし")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="month",
            name="month",
            field=models.CharField(
                choices=[
                    ("1月", "1月"),
                    ("2月", "2月"),
                    ("3月", "3月"),
                    ("4月", "4月"),
                    ("5月", "5月"),
                    ("6月", "6月"),
                    ("7月", "7月"),
                    ("8月", "8月"),
                    ("9月", "9月"),
                    ("10月", "10月"),
                    ("11月", "11月"),
                    ("12月", "12月"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
