# Generated by Django 4.1.1 on 2022-12-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alcoholchecks", "0003_alter_info_carnumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="carnumber",
            field=models.IntegerField(choices=[(3080, 3080)]),
        ),
    ]
