# Generated by Django 4.1.1 on 2023-10-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alcoholchecks", "0004_alter_info_carnumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="info",
            name="how_to",
            field=models.CharField(default="対面", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="info",
            name="varified_by",
            field=models.CharField(default="武村 義治", max_length=10),
            preserve_default=False,
        ),
    ]
