# Generated by Django 4.1.1 on 2022-09-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alcoholchecks", "0004_month_owner_alter_info_alcohol_alter_month_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="month",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
