# Generated by Django 4.1.1 on 2023-10-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alcoholchecks", "0005_info_how_to_info_varified_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="how_to",
            field=models.CharField(
                choices=[("対面", "対面"), ("ビデオ通話", "ビデオ通話")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="info",
            name="varified_by",
            field=models.CharField(
                choices=[("武村 義治", "武村 義治"), ("武村 俊二", "武村 俊二")], max_length=10
            ),
        ),
    ]
