# Generated by Django 4.1.1 on 2022-09-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alcoholchecks", "0005_month_date_added"),
    ]

    operations = [
        migrations.AddField(
            model_name="info",
            name="carnumber",
            field=models.CharField(
                choices=[
                    ("6882", "6882"),
                    ("2151", "2151"),
                    ("2532", "2532"),
                    ("5173", "5173"),
                    ("5999", "5999"),
                    ("386", "386"),
                    ("783", "783"),
                    ("2569", "2569"),
                    ("777", "777"),
                    ("3080", "3080"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="info",
            name="alcohol",
            field=models.CharField(
                choices=[("アルコール検知あり", "あり"), ("アルコール検知なし", "なし")],
                max_length=20,
                null=True,
            ),
        ),
    ]
