# Generated by Django 4.1.1 on 2022-09-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alcoholchecks", "0006_info_carnumber_alter_info_alcohol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="alcohol",
            field=models.CharField(
                choices=[
                    ("アルコール検知: 0.00mg", "0.00mg"),
                    ("アルコール検知: 0.15mg未満", "0.15mg未満"),
                    ("アルコール検知: 0.15mg以上", "0.15mg以上"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
