# Generated by Django 4.1.1 on 2022-12-04 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("alcoholchecks", "0007_alter_info_alcohol"),
    ]

    operations = [
        migrations.AddField(
            model_name="info",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="info",
            name="alcohol",
            field=models.CharField(
                choices=[
                    ("アルコール検知: 0.00mg", "0.00mg"),
                    ("アルコール検知: 0.15mg未満", "0.15mg未満"),
                    ("アルコール検知: 0.15mg以上", "0.15mg以上"),
                ],
                default="アルコール検知: 0.00mg",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="info",
            name="carnumber",
            field=models.CharField(
                choices=[
                    ("6882", "6882"),
                    ("2151", "2151"),
                    ("2532", "2532"),
                    ("5173", "5173"),
                    ("5999", "5999"),
                    ("386", "386"),
                    ("783", "783"),
                    ("2569", "2569"),
                    ("777", "777"),
                    ("3080", "3080"),
                ],
                default="0",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="info",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="info",
            name="month",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="alcoholchecks.month",
            ),
            preserve_default=False,
        ),
    ]
